version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xccloud

  redis:
    image: redis    #标明镜像ID,本地如果没有会尝试pull下来


  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"

  nginx:
    image: nginx:1.15
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx:/etc/nginx/conf.d/
      - ./cert.d:/etc/nginx/cert.d/
    ports:
      - "8010:80"

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     links:
      - mysql:mysql
     ports:
      - 8020:80
     environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: xccloudd
      PMA_HOST: mysql

   



